version: "3.8"
services:

  ui:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MARVEL_API_URL: ${MARVEL_API_URL}
      BACKEND_API_URL: ${BACKEND_API_URL_PATH}${BACKEND_PORT}

    ports:
      - ${UI_LOCAL_PORT}:${UI_DOCKER_PORT}
    volumes:
      - ./src:/app/src

volumes:
  ui: